### ISSUE TITLE
Sort element like they are in the json

### ISSUE THREAD

**Issue by FansubDB** [pureexe/fansubdb-browser#1]
On https://fansubdb.pureapp.in.th/#/fr/2014/automne
I saw that for exemple Kiseijuu is before Dungeon.

Is it normal? No way to reorder/let the normal order?

**Comment by pureexe** [comment]
Confirm: Order have changed on Firefox And Mircrosoft edge when you load page first time. still don't known why.

(But worked fine on Chrome and Opera)

**Comment by pureexe** [comment]
@FansubDB solve on d4bbf30
Template was loading in asynchronize. so order is uncontrollable when some card load complete before previous card. so I add code to wait for card loading complete before loading next card. 

Note: load card complete is just load from `card.tpl` but not wait for image load.

**Comment by FansubDB** [comment]
yes, so I close issue
