### ISSUE TITLE
404 Not found

### ISSUE THREAD

**Issue by FansubDB** [pureexe/fansubdb-browser#2]
Hey

I've forked your repo into https://github.com/FansubDB/fanapp-browser, and has activate the github page on the master.

But when going to https://fansubdb.github.io/fanapp-browser/ I have a 404 error.

Do you know why?

Thank you :)

**Comment by pureexe** [comment]
@FansubDB 
my route in app.js is writing for place file at root of domain .
to use with sub directory in domain

in app.js
- change  `^(?:|#|\/#)/$` to `^fanapp-browser(?:|#|\/#)/`
- change `^/#/:lang(?:|\/)$` to `^/fanapp-browser/#/:lang(?:|\/)$`
- change  `^/#/:lang/:year/:season(?:|\/)$` to `^/fanapp-browser/#/:lang/:year/:season(?:|\/)$`
should be work fine.

**Comment by FansubDB** [comment]
It seems to not working :/
Do you see any problem?

**Comment by pureexe** [comment]
Only problem on index page.

try to change `'^' + folder + '(?:|#|\/#)/$'` to `'^/' + folder + '(?:|#|\/#|\/#\/)$'`
should be work.

for other pages, it's worked fine.
https://fansubdb.github.io/fanapp-browser/#/th
https://fansubdb.github.io/fanapp-browser/#/th/2017/spring

**Comment by FansubDB** [comment]
thank you
